[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_guess = "6vWgxZqyG7eMN4HUGzKepGLxNjQNhFSPxznTB7a5AfnP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tropicaldog17/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
